steps = 0
state = 'A'

[table]
[table.A]
0 = ['1','R','B']
1 = ['1','L','B']
[table.B]
0 = ['1','L','A']
1 = ['1','R','HALT']

[tape]
left = ['0','0','0','0','0','0','0','0']
center = '0'
right = ['0','0','0','0','0','0','0','0']
