steps = 0
state = 'A'

[table]
[table.A]
0 = ['1','R','B']
1 = ['1','L','C']
[table.B]
0 = ['1','R','C']
1 = ['1','R','B']
[table.C]
0 = ['1','R','D']
1 = ['0','L','E']
[table.D]
0 = ['1','L','A']
1 = ['1','L','D']
[table.E]
0 = ['1','R','HALT']
1 = ['0','L','A']

[tape]
left = ['0','0','0','0','0','0','0','0']
center = '0'
right = ['0','0','0','0','0','0','0','0']
