steps = 0
state = 'A'

[table]
[table.A]
0 = ['1','R','B']
1 = ['1','R','HALT']
[table.B]
0 = ['1','L','B']
1 = ['0','R','C']
[table.C]
0 = ['1','L','C']
1 = ['1','L','A']

[tape]
left = ['0','0','0','0','0','0','0','0']
center = '0'
right = ['0','0','0','0','0','0','0','0']
